name: Admin Dashboard CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: admin-dashboard/pnpm-lock.yaml
    
    - name: Install dependencies
      working-directory: ./admin-dashboard
      run: pnpm install --frozen-lockfile
    
    - name: Lint
      working-directory: ./admin-dashboard
      run: pnpm lint
    
    - name: Build
      working-directory: ./admin-dashboard
      run: pnpm build